FROM python:3.12-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /qms_service

COPY . /qms_service

EXPOSE 8080

RUN python3 -m venv venv && source venv/bin/activate
RUN pip3 install -r configs/requirements.txt


CMD uvicorn main:app --host 0.0.0.0 --port 8080